name: CICD
on:
  push:
    branches: [ "master" ]

jobs:

  CICD:

    runs-on: ubuntu-latest

    steps:
      - name: Add the environment file
      - uses: actions/checkout@v4
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env.production
          
      - name: Login to Docker Hub
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - nmae: Build and Push to Docker Hub
        uses: docker/build-push-action@v6
        with:   
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fyp_webapp:latest
      
      - name: Deploy to ECS
        run: aws ecs update-service --cluster ${{ vars.ECS_CLUSTER_NAME }} --service ${{ vars.ECS_SERVICE_NAME }} --force-new-deployment